name: Run Tests on Pull Request

on:
  pull_request:
    branches:
      - develop
      - feature

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install Dependencies
      run: npm run render-build

    - name: Start App
      run: npm run start

    - name: Run Cypress Component test
      run: npm run test-component
